/**
 * Contract ABIs, generated from the compiled artifacts.
 *
 * This file is written by `packages/hardhat/scripts/generateTsAbis.ts` and checked in so
 * that the browser bundle does not need the Hardhat artifact directory. It is verified
 * against the compiled artifact by `packages/hardhat/test/abi.test.ts`, so it cannot
 * drift from the contract without failing the suite.
 *
 * Do not edit by hand.
 */

/** PricedAssetRegistry — generated by `yarn generate:abis`. Do not edit; run `test/abi.test.ts` to check it. */
export const PRICED_ASSET_REGISTRY_ABI = [
  {
    inputs: [
      {
        internalType: "contract IPythOracle",
        name: "oracle_",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "maxDeviationBps_",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "maxPriceAgeSeconds_",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordId",
        type: "bytes32",
      },
    ],
    name: "AlreadyRecorded",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "deviationBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "maxDeviationBps",
        type: "uint16",
      },
    ],
    name: "DeviationTooHigh",
    type: "error",
  },
  {
    inputs: [],
    name: "EmptyAttestationHash",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "int32",
        name: "attested",
        type: "int32",
      },
      {
        internalType: "int32",
        name: "live",
        type: "int32",
      },
    ],
    name: "ExpoMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int32",
        name: "expo",
        type: "int32",
      },
    ],
    name: "ExponentOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "MathDivisionByZero",
    type: "error",
  },
  {
    inputs: [],
    name: "MathOverflow",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "int64",
        name: "price",
        type: "int64",
      },
    ],
    name: "NonPositivePrice",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "NotAuthorised",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "NotOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "maxDeviationBps",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "maxPriceAgeSeconds",
        type: "uint64",
      },
    ],
    name: "PolicyOutOfRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "ageSeconds",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "maxPriceAgeSeconds",
        type: "uint64",
      },
    ],
    name: "PriceStale",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "attested",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "live",
        type: "uint32",
      },
    ],
    name: "PublishTimeMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroUnits",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "recordId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "attestationHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "assetToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "registrant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "units",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "int64",
        name: "price",
        type: "int64",
      },
      {
        indexed: false,
        internalType: "int64",
        name: "conf",
        type: "int64",
      },
      {
        indexed: false,
        internalType: "int32",
        name: "expo",
        type: "int32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "publishTime",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "deviationBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "priceAgeSeconds",
        type: "uint64",
      },
    ],
    name: "IssuanceRecorded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint16",
        name: "maxDeviationBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "maxPriceAgeSeconds",
        type: "uint64",
      },
    ],
    name: "PolicyUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    name: "RegistrantUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_ALLOWED_DEVIATION_BPS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_ALLOWED_MAX_PRICE_AGE_SECONDS",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_PRICE_EXPONENT",
    outputs: [
      {
        internalType: "int32",
        name: "",
        type: "int32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_PRICE_EXPONENT",
    outputs: [
      {
        internalType: "int32",
        name: "",
        type: "int32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "authorizedRegistrants",
    outputs: [
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "units",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "int64",
            name: "price",
            type: "int64",
          },
          {
            internalType: "int64",
            name: "conf",
            type: "int64",
          },
          {
            internalType: "int32",
            name: "expo",
            type: "int32",
          },
          {
            internalType: "uint32",
            name: "publishTime",
            type: "uint32",
          },
        ],
        internalType: "struct PricedAssetRegistry.Observation",
        name: "attested",
        type: "tuple",
      },
    ],
    name: "checkAttestation",
    outputs: [
      {
        internalType: "bool",
        name: "acceptable",
        type: "bool",
      },
      {
        internalType: "bytes4",
        name: "reason",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "units",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "int64",
            name: "price",
            type: "int64",
          },
          {
            internalType: "int64",
            name: "conf",
            type: "int64",
          },
          {
            internalType: "int32",
            name: "expo",
            type: "int32",
          },
          {
            internalType: "uint32",
            name: "publishTime",
            type: "uint32",
          },
        ],
        internalType: "struct PricedAssetRegistry.Observation",
        name: "attested",
        type: "tuple",
      },
    ],
    name: "checkAttestationStrict",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int64",
        name: "attested",
        type: "int64",
      },
      {
        internalType: "int64",
        name: "live",
        type: "int64",
      },
    ],
    name: "deviationBpsOf",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordId",
        type: "bytes32",
      },
    ],
    name: "hasRecord",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
    ],
    name: "livePrice",
    outputs: [
      {
        components: [
          {
            internalType: "int64",
            name: "price",
            type: "int64",
          },
          {
            internalType: "int64",
            name: "conf",
            type: "int64",
          },
          {
            internalType: "int32",
            name: "expo",
            type: "int32",
          },
          {
            internalType: "uint32",
            name: "publishTime",
            type: "uint32",
          },
        ],
        internalType: "struct PricedAssetRegistry.Observation",
        name: "observation",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxDeviationBps",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxPriceAgeSeconds",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oracle",
    outputs: [
      {
        internalType: "contract IPythOracle",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oracleValidTimePeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "policy",
    outputs: [
      {
        internalType: "uint16",
        name: "deviationBps_",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "maxPriceAgeSeconds_",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
    ],
    name: "priceE18",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "recordCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "recordIdAt",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "attestationHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "assetToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "units",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "int64",
            name: "price",
            type: "int64",
          },
          {
            internalType: "int64",
            name: "conf",
            type: "int64",
          },
          {
            internalType: "int32",
            name: "expo",
            type: "int32",
          },
          {
            internalType: "uint32",
            name: "publishTime",
            type: "uint32",
          },
        ],
        internalType: "struct PricedAssetRegistry.Observation",
        name: "attested",
        type: "tuple",
      },
    ],
    name: "recordIssuance",
    outputs: [
      {
        internalType: "bytes32",
        name: "recordId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordId",
        type: "bytes32",
      },
    ],
    name: "recordOf",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "attestationHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "feedId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "assetToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "registrant",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "units",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "int64",
                name: "price",
                type: "int64",
              },
              {
                internalType: "int64",
                name: "conf",
                type: "int64",
              },
              {
                internalType: "int32",
                name: "expo",
                type: "int32",
              },
              {
                internalType: "uint32",
                name: "publishTime",
                type: "uint32",
              },
            ],
            internalType: "struct PricedAssetRegistry.Observation",
            name: "observed",
            type: "tuple",
          },
          {
            internalType: "uint16",
            name: "deviationBps",
            type: "uint16",
          },
          {
            internalType: "uint64",
            name: "priceAgeSeconds",
            type: "uint64",
          },
          {
            internalType: "uint32",
            name: "recordedAt",
            type: "uint32",
          },
        ],
        internalType: "struct PricedAssetRegistry.IssuanceRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "maxDeviationBps_",
        type: "uint16",
      },
      {
        internalType: "uint64",
        name: "maxPriceAgeSeconds_",
        type: "uint64",
      },
    ],
    name: "setPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    name: "setRegistrant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "units",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "tokenDecimals",
        type: "uint8",
      },
    ],
    name: "valueOfBaseUnits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
