/**
 * Generates the contract ABI the browser bundle uses.
 *
 * Usage:
 *   yarn hardhat typechain:abis      # or: yarn workspace @sh/hardhat generate:abis
 *
 * Writes `packages/shared/src/abi/generated.ts`.
 *
 * The file is checked in rather than imported from the Hardhat artifacts at runtime,
 * because the Next.js bundle must not depend on a Hardhat build directory existing —
 * and because a reviewer can read exactly which ABI the app ships. That only stays
 * honest if drift is impossible, so `test/abi.test.ts` compares this file against the
 * compiled artifact and fails when they differ.
 *
 * Regenerate it in the same commit as any contract change.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import hre from "hardhat";

/** Contracts whose ABI the app needs. The registry is the only one the browser calls. */
const CONTRACTS = ["PricedAssetRegistry"] as const;

const OUTPUT = path.join(hre.config.paths.root, "..", "shared", "src", "abi", "generated.ts");

async function main(): Promise<void> {
  const entries: string[] = [];

  for (const name of CONTRACTS) {
    const artifact = await hre.artifacts.readArtifact(name);
    entries.push(
      `/** ${name} — generated by \`yarn generate:abis\`. Do not edit; run \`test/abi.test.ts\` to check it. */\n` +
        `export const ${constName(name)}_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    );
    console.log(`  ${name}: ${artifact.abi.length} ABI entries`);
  }

  const contents = `/**
 * Contract ABIs, generated from the compiled artifacts.
 *
 * This file is written by \`packages/hardhat/scripts/generateTsAbis.ts\` and checked in so
 * that the browser bundle does not need the Hardhat artifact directory. It is verified
 * against the compiled artifact by \`packages/hardhat/test/abi.test.ts\`, so it cannot
 * drift from the contract without failing the suite.
 *
 * Do not edit by hand.
 */

${entries.join("\n\n")}
`;

  await mkdir(path.dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, contents);
  console.log(`\n  Wrote ${path.relative(process.cwd(), OUTPUT)}`);
}

/** `PricedAssetRegistry` -> `PRICED_ASSET_REGISTRY`. */
function constName(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

main().catch((error: unknown) => {
  console.error(`\nABI generation failed: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
